2023-11-28 22:31:55,323:__main__:ERROR:Tried to divide by zero
2023-11-28 22:32:56,758:__main__:ERROR:Tried to divide by zero
Traceback (most recent call last):
  File "D:\Coding\robotics\Python\log_sample.py", line 36, in divide
    result =  x / y
ZeroDivisionError: division by zero
2023-11-28 22:34:06,481:__main__:ERROR:Tried to divide by zero
Traceback (most recent call last):
  File "D:\Coding\robotics\Python\log_sample.py", line 39, in divide
    result =  x / y
ZeroDivisionError: division by zero
2023-11-28 22:34:46,319:__main__:ERROR:Tried to divide by zero
Traceback (most recent call last):
  File "D:\Coding\robotics\Python\log_sample.py", line 40, in divide
    result =  x / y
ZeroDivisionError: division by zero
